In [1]:
import pandas as pd

In [4]:
df=pd.read_csv("emp Data.csv")

In [ ]:
df

,Sn,Emp First Name,Employee last name,Unnamed: 3,City,Full name,left,Right,mid,Todays Date,Todays Date and Time,Date(),Time(),Salary increment,Percentage,RoundUP,RoundDown,Promotions,Salary Increment
0,1.0,Ram,A,20000,Bangalore,RamA,R,m,am,9/17/2025,9/17/2025 23:15:28,9/9/2025,10:31:00 AM,1000.0,74.222,74.3,74.2,promoted,2000.0
1,2.0,Alex,F,45000,Delhi,AlexF,A,x,lex,9/17/2025,9/17/2025 23:15:28,9/9/2025,10:31:00 AM,1000.0,65.220,65.3,65.2,promoted,4500.0
2,3.0,Salamaan,Khan,50000,Patna,SalamaanKhan,S,n,ala,9/17/2025,9/17/2025 23:15:28,9/9/2025,10:31:00 AM,1000.0,84.400,84.4,84.4,promoted,5000.0
3,4.0,Yograj,Gupla,15000,Punjab,YograjGupla,Y,j,ogr,9/17/2025,9/17/2025 23:15:28,9/9/2025,10:31:00 AM,1000.0,74.222,74.3,74.2,not promoted),1500.0
4,5.0,Krish,Sharma,10000,Delhi,KrishSharma,K,h,ris,9/17/2025,9/17/2025 23:15:28,9/9/2025,10:31:00 AM,1000.0,65.220,65.3,65.2,not promoted),1000.0
5,6.0,Salika,O,45000,Mumbai,SalikaO,S,a,ali,9/17/2025,9/17/2025 23:15:28,9/9/2025,10:31:00 AM,1000.0,85.400,85.4,85.4,promoted,4500.0
6,7.0,Pooja,Kumari,20000,Chennai,PoojaKumari,P,a,ooj,9/17/2025,9/17/2025 23:15:28,9/9/2025,10:31:00 AM,1000.0,74.222,74.3,74.2,promoted,2000.0
7,8.0,Pratiksha,Sing,50000,Pune,PratikshaSing,P,a,rat,9/17/2025,9/17/2025 23:15:28,9/9/2025,10:31:00 AM,1000.0,65.220,65.3,65.2,promoted,5000.0
8,9.0,Komal,Khan,80000,Madurai,KomalKhan,K,l,oma,9/17/2025,9/17/2025 23:15:28,9/9/2025,10:31:00 AM,1000.0,85.400,85.4,85.4,promoted,8000.0
9,10.0,ganeesh,Sharma,66000,Ayodhya,ganeeshSharma,g,h,ane,9/17/2025,9/17/2025 23:15:28,9/9/2025,10:31:00 AM,1000.0,85.400,85.4,85.4,promoted,6600.0
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,TotalSalary,401000,Person from bangalore,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,Average Salary,40100,[person from delhi,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,Average Salary,80000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,NaN,Average Salary,10000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,NaN,NaN,NaN,Komal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,NaN,NaN,Chart,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:

df.to_csv("titanic.csv, index=false")
df

,Sn,Emp First Name,Employee last name,Unnamed: 3,City,Full name,left,Right,mid,Todays Date,Todays Date and Time,Date(),Time(),Salary increment,Percentage,RoundUP,RoundDown,Promotions,Salary Increment
0,1.0,Ram,A,20000,Bangalore,RamA,R,m,am,9/17/2025,9/17/2025 23:15:28,9/9/2025,10:31:00 AM,1000.0,74.222,74.3,74.2,promoted,2000.0
1,2.0,Alex,F,45000,Delhi,AlexF,A,x,lex,9/17/2025,9/17/2025 23:15:28,9/9/2025,10:31:00 AM,1000.0,65.220,65.3,65.2,promoted,4500.0
2,3.0,Salamaan,Khan,50000,Patna,SalamaanKhan,S,n,ala,9/17/2025,9/17/2025 23:15:28,9/9/2025,10:31:00 AM,1000.0,84.400,84.4,84.4,promoted,5000.0
3,4.0,Yograj,Gupla,15000,Punjab,YograjGupla,Y,j,ogr,9/17/2025,9/17/2025 23:15:28,9/9/2025,10:31:00 AM,1000.0,74.222,74.3,74.2,not promoted),1500.0
4,5.0,Krish,Sharma,10000,Delhi,KrishSharma,K,h,ris,9/17/2025,9/17/2025 23:15:28,9/9/2025,10:31:00 AM,1000.0,65.220,65.3,65.2,not promoted),1000.0
5,6.0,Salika,O,45000,Mumbai,SalikaO,S,a,ali,9/17/2025,9/17/2025 23:15:28,9/9/2025,10:31:00 AM,1000.0,85.400,85.4,85.4,promoted,4500.0
6,7.0,Pooja,Kumari,20000,Chennai,PoojaKumari,P,a,ooj,9/17/2025,9/17/2025 23:15:28,9/9/2025,10:31:00 AM,1000.0,74.222,74.3,74.2,promoted,2000.0
7,8.0,Pratiksha,Sing,50000,Pune,PratikshaSing,P,a,rat,9/17/2025,9/17/2025 23:15:28,9/9/2025,10:31:00 AM,1000.0,65.220,65.3,65.2,promoted,5000.0
8,9.0,Komal,Khan,80000,Madurai,KomalKhan,K,l,oma,9/17/2025,9/17/2025 23:15:28,9/9/2025,10:31:00 AM,1000.0,85.400,85.4,85.4,promoted,8000.0
9,10.0,ganeesh,Sharma,66000,Ayodhya,ganeeshSharma,g,h,ane,9/17/2025,9/17/2025 23:15:28,9/9/2025,10:31:00 AM,1000.0,85.400,85.4,85.4,promoted,6600.0
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,TotalSalary,401000,Person from bangalore,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,Average Salary,40100,[person from delhi,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,Average Salary,80000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,NaN,Average Salary,10000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,NaN,NaN,NaN,Komal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,NaN,NaN,Chart,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN