In [1]:
# Array Creation

In [2]:
import numpy
arr = numpy.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]

In [3]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]

In [4]:
import numpy as np
arr1 = np.arange(1,10)
print(arr1)

[1 2 3 4 5 6 7 8 9]

In [5]:
import numpy as np
arr1 = np.arange(1,10,2)
print(arr1)

[1 3 5 7 9]

In [6]:
import numpy as np
arr1 = np.arange(1,10,5)
print(arr1)

[1 6]

In [8]:
import numpy as np
arr1 = np.arange(1,12,5)
print(arr1)

[ 1  6 11]

In [18]:
import numpy as ram
arr2=ram.linspace(0,10,5)
print(arr2)

[ 0.   2.5  5.   7.5 10. ]

In [19]:
arr3=np.zeros((2,3))
print(arr3)

[[0. 0. 0.]
 [0. 0. 0.]]

In [22]:
arr3=np.ones((3,3))
print(arr3)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

In [24]:
arr4=np.eye(4)
print(arr4)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

In [27]:
arr5=np.empty(10)
print(arr5)

[5.06275116e-310 0.00000000e+000 0.00000000e+000 0.00000000e+000
 6.68428674e-310 7.63105729e+169 1.38058673e-047 5.33741640e-091
 3.50820527e-033 6.68436814e-310]

In [28]:
# Array Manipulation

In [34]:
import numpy as np
arr = np.arange(12)
res = np.reshape(arr,(3,4))
print(res)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

In [39]:
import numpy as np
arr = np.arange(1,4)
res = np.resize(arr,30)
print(res)

[1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3 1 2 3]

In [42]:
srr = np.arange(0,8)
res = np.reshape(srr,(4,2))
print(res)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]

In [45]:
import numpy as np
arr = np.array(
    [[1,2,3],
    [4,5,6]]
)

print(arr)

[[1 2 3]
 [4 5 6]]

In [46]:
import numpy as np
arr = np.array(
    [[1,2,3],
    [4,5,6]]
)

res=arr.flatten()
print(res)

[1 2 3 4 5 6]

In [51]:
import numpy as np
arr1 = np.array(
    [[1,2,3],
    [4,5,6]]
)
arr2 = np.array(
    [[10,20,30],
    [40,50,60]]
)

res = np.vstack((arr1,arr2))
print(res)

[[ 1  2  3]
 [ 4  5  6]
 [10 20 30]
 [40 50 60]]

In [52]:
import numpy as np
arr1 = np.array(
    [[1,2,3],
    [4,5,6]]
)
arr2 = np.array(
    [[10,20,30],
    [40,50,60]]
)

res = np.hstack((arr1,arr2))
print(res)

[[ 1  2  3 10 20 30]
 [ 4  5  6 40 50 60]]

In [55]:
import numpy as np
arr1 = np.array(
    [[1,2,3],
     [1,2,3]]
)
arr2 = np.array(
    [[1,2,3],
     [1,2,3]]
)

res = np.vstack((arr1,arr2))
print(res)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]

In [ ]:
"""
sum()
mean()
std()
var()
min()
max()
argmin()
argmax()
exp()
log()
"""

In [56]:
import numpy as np
arr1 = np.array(
    [[1,2,3],
     [1,2,3]]
)

res = np.sum(arr1)
print(res)

12

In [57]:
import numpy as np
arr1 = np.array([10,30,20])
res = np.sum(arr1)
print(res)

60

In [58]:
import numpy as np
arr1 = np.array([10,30,20])
res = np.mean(arr1)
print(res)

20.0

In [59]:
import numpy as np
arr1 = np.array([10,30])
res = np.mean(arr1)
print(res)

20.0

In [61]:
import numpy as np
arr1 = np.array([10,30])
res = np.max(arr1)
print(res)

30

In [60]:
import numpy as np
arr1 = np.array([10,30])
res = np.min(arr1)
print(res)

10

In [62]:
import numpy as np
arr1 = np.array([
    [1,2,3],
    [2,3,4]

]
)
res = np.sum(arr1,axis=0)
print(res)

[3 5 7]

In [63]:
import numpy as np
arr1 = np.array([
    [1,2,3],
    [2,3,4]

]
)
res = np.sum(arr1,axis=1)
print(res)

[6 9]

In [65]:
import numpy as np
arr1 = np.array([
    [1,2,3],
    [2,3,4]

]
)
res = np.sum(arr1,axis=1)
print(res)

[6 9]

In [66]:
import numpy as np
arr1 = np.array([
    [1,2,3],
    [2,3,4]

]
)
res = np.std(arr1)
print(res)

0.9574271077563381

In [67]:
import numpy as np
arr1 = np.array([
    [1,2,3],
    [2,3,4]

]
)
res = np.var(arr1)
print(res)

0.9166666666666666

In [68]:
import numpy as np
arr1 = np.array([1,2,3])
res = np.exp(arr1)
print(res)

[ 2.71828183  7.3890561  20.08553692]

In [77]:
import numpy as np
arr1 = np.array([90,20,30,10])
res = np.argmin(arr1)
print(res)

3

In [73]:
import numpy as np
arr1 = np.array([10,90,20,30,10])
res = np.argmax(arr1)
print(res)

1

In [74]:
import numpy as np
arr1 = np.array([10,90,20,30,10])
res = np.log(arr1)
print(res)

[2.30258509 4.49980967 2.99573227 3.40119738 2.30258509]

In [78]:
arr = np.random.rand(6)
print(arr)

[0.55644111 0.35440269 0.37021534 0.73217258 0.87443988 0.26285434]

In [82]:
arr = np.random.randint(1,10,4)
print(arr)

[5 3 9 1]

In [83]:
arr = np.random.randn(5)
print(arr)

[ 0.91681705  0.53506748  0.49409517 -0.8939029  -0.17774384]

In [84]:
import numpy as np
arr1 = np.array([10,90,20])
arr2 = np.array([2,2,2])
res = np.dot(arr1,arr2)
print(res)

240

In [89]:
import numpy as np
arr1 = np.array([
    [1,2],
     [3,4]])
arr2 = np.array([
    [5,6],
     [7,8]])
res = np.matmul(arr1,arr2)
print(res)

[[19 22]
 [43 50]]

In [ ]:
[1,2]  [5,6]
[3,4]  [7,8]

#first row * first column
# 1*5+2*7 =19
# 1*6+2*8 =22
# 3*5+4*7 =43
# 3*6+4*8 =50

In [91]:
import numpy as np
arr1 = np.array([10,90,20])
res = np.append(arr1,2)
print(res)

[10 90 20  2]

In [92]:
import numpy as np
arr1 = np.array([10,90,20])
res = np.append(arr1,[20,30,40])
print(res)

[10 90 20 20 30 40]

In [95]:
import numpy as np
arr = np.array([10,90,20])
arr[0]=100
print(arr)

[100  90  20]

In [96]:
arr=np.random.rand(3,3)
print(arr)

[[0.43151637 0.78714282 0.55211694]
 [0.47976693 0.05405919 0.1052972 ]
 [0.56891468 0.92288547 0.68414643]]

In [97]:
arr1 = numpy.random[3:3]
print(arr1)

TypeError: 'module' object is not subscriptable

In [100]:
import numpy as np
arr=np.random.randint(0,10,9)
res=np.reshape(arr,(3,3))
print(res)

[[4 6 2]
 [4 2 7]
 [8 9 2]]

In [101]:
import numpy
arr = numpy.random.randint(0,10,size=(3,3))
print(arr)

[[2 5 2]
 [2 9 5]
 [3 6 1]]

In [109]:
import numpy as np
arr = np.random.randint(0,16,16)
res = np.reshape(arr,(4,4))
print(res)

[[ 8  1  3  3]
 [ 2  6  0  7]
 [ 5  3 13 12]
 [ 8  9 10  9]]

In [110]:
import pandas as pd

In [112]:
data = {
    'Name':['Ram','Krish','Salmaan'],
    'Age':[10,11,12],
    'Fav Movie':['Baahubali','Hanuman','Pathan']
}

df=pd.DataFrame(data)
display(df)

      Name  Age  Fav Movie
0      Ram   10  Baahubali
1    Krish   11    Hanuman
2  Salmaan   12     Pathan

In [113]:
df['Roles']=['Eng','Doctor','Pilot']
display(df)

      Name  Age  Fav Movie   Roles
0      Ram   10  Baahubali     Eng
1    Krish   11    Hanuman  Doctor
2  Salmaan   12     Pathan   Pilot

In [115]:
filterData = df['Age']>=11
display(filterData)

0    False
1     True
2     True
Name: Age, dtype: bool

In [116]:
filterData = df[df['Age']>=11]
display(filterData)

      Name  Age Fav Movie   Roles
1    Krish   11   Hanuman  Doctor
2  Salmaan   12    Pathan   Pilot

In [118]:
display(df)

      Name  Age  Fav Movie   Roles
0      Ram   10  Baahubali     Eng
1    Krish   11    Hanuman  Doctor
2  Salmaan   12     Pathan   Pilot

In [119]:
df.to_csv("student.csv",index=False)