In [ ]:
#array creation

In [ ]:
import numpy
arr=numpy.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]

In [ ]:
import numpy as np
arr1=np.arange(1,10,2)
print(arr1)

[1 3 5 7 9]

In [ ]:
import numpy as np
arr1=np.arange(1,10,5)
print(arr1)

[1 6]

In [ ]:
arr2=np.linspace(0,10,10)
print(arr2)

[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]

In [ ]:
arr3=np.zeros((2,3))
print(arr3)

[[0. 0. 0.]
 [0. 0. 0.]]

In [ ]:
arr3=np.zeros((5,10))
print(arr3)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

In [ ]:
arr3=np.ones((5,10))
print(arr3)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

In [ ]:
arr4=np.eye(4)
print(arr4)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

In [ ]:
arr5=np.empty(10)
print(arr5)

[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]

In [ ]:
import numpy as np
arr=np.arange(15)
res=np.reshape(arr,(3,5))
print(res)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

In [ ]:
import numpy as np
arr=np.arange(12)
res=np.resize(arr,2)
print(res)

[0 1]

In [ ]:
import numpy as np
arr=np.array(
   [ [1,2,3,],
    [4,5,6]]
)
print(arr)

[[1 2 3]
 [4 5 6]]

In [ ]:
import numpy as np
arr=np.array(
   [ [1,2,3,],
    [4,5,6]]
)
res=arr.flatten()
print(res)

[1 2 3 4 5 6]

In [ ]:
import numpy as np
arr1=np.array(
   [ [1,2,3,],
    [4,5,6]]
)
arr2=np.array(
   [ [10,20,30,],
    [40,50,60]]
)

res=np.vstack((arr1,arr2))
print(res)

[[ 1  2  3]
 [ 4  5  6]
 [10 20 30]
 [40 50 60]]

In [ ]:
import numpy as np
arr1=np.array(
   [ [1,2,3,],
    [4,5,6]]
)
arr2=np.array(
   [ [10,20,30,],
    [40,50,60]]
)

res=np.hstack((arr1,arr2))
print(res)

[[ 1  2  3 10 20 30]
 [ 4  5  6 40 50 60]]

In [ ]:
import numpy as np
arr1=np.array(
    [[1,2,3],
     [1,2,3]]
)
res=np.sum(arr1)
print(res)

12

In [ ]:
import numpy as np
arr1=np.array( [10,20,30])
res=np.sum(arr1)
print(res)

60

In [ ]:
import numpy as np
arr1=np.array( [10,20,30])
res=np.mean(arr1)
print(res)

20.0

In [ ]:
import numpy as np
arr1=np.array( [10,20,30])
res=np.max(arr1)
print(res)

30

In [ ]:
import numpy as np
arr1=np.array( [10,20,30])
res=np.min(arr1)
print(res)

10

In [ ]:
import numpy as np
arr1=np.array([
    [1,2,3],
    [2,3,4]]
)
res=np.sum(arr1,axis=0)
print(res)

[3 5 7]

In [ ]:
import numpy as np
arr1=np.array([
    [1,2,3],
    [2,3,4]]
)
res=np.sum(arr1,axis=0)
print(res)

[6 9]

In [ ]:
import numpy as np
arr1=np.array([
    [1,2,3],
    [2,3,4]]
)
res=np.std(arr1)
print(res)

0.9574271077563381

In [ ]:
import numpy as np
arr1=np.array([1,2,3])
res=np.exp(arr1)
print(res)

[ 2.71828183  7.3890561  20.08553692]

In [ ]:
import numpy as np
arr1=np.array([1,2,3])
res=np.var(arr1)
print(res)

0.6666666666666666

In [ ]:
import numpy as np
arr1=np.array([1,2,3])
res=np.(arr1)
print(res)

In [ ]:
import numpy as np
arr1=np.array([10,20,30,40,50])
res=np.argmin(arr1)
print(res)

0

In [ ]:
import numpy as np
arr1=np.array([90,80,60,59,58])
res=np.argmin(arr1)
print(res)

4

In [20]:
import numpy as np
arr1=np.array([90,80,60,59,100])
res=np.argmax(arr1)
print(res)

4

In [1]:
import numpy as np
arr1=np.array([90,80,60,80,100])
res=np.log(arr1)
print(res)

[4.49980967 4.38202663 4.09434456 4.38202663 4.60517019]

In [5]:
arr=np.random.rand(6)
print(arr)

[0.76225534 0.21715485 0.13074114 0.66165434 0.33236058 0.86935972]

In [8]:
arr=np.random.randint(1,20,5)
print(arr)

[ 3 11  3 14  5]

In [10]:
arr=np.random.randn(5)
print(arr)

[-0.56440048 -0.88935135  1.36699979 -2.04977849  2.42662282]

In [22]:
import numpy as np
arr1=np.array([10,90,20,])
arr2=np.array([2,2,2])
res=np.dot(arr1,arr2)
print(res)

240

In [ ]:
import numpy as np
arr1=np.array([10,90,20,])
arr2=np.array([2,2,2])
res=np.dot(arr1,arr2)
print(res)

In [28]:
import numpy as np
arr1=np.array([[1,2],
               [3,4]])
arr2=np.array([[5,6],
              [7,8]])
res=np.matmul(arr1,arr2)
print(res)

[[19 22]
 [43 50]]

In [36]:
import numpy  as np
arr1=np.array([10,90,20])
res=np.append(arr1,1000)
print(res)

[  10   90   20 1000]

In [33]:
import numpy  as np
arr1=np.array([10,90,20])
res=np.append(arr1,[20,100,1000])
print(res)

[  10   90   20   20  100 1000]

In [5]:
import numpy as np
arr=np.array([10,90,20])
arr[1]=100
print(arr)

[ 10 100  20]

In [19]:
import numpy as np
arr=np.random.randint(0,5,9)

print(arr)

[4 4 3 2 4 4 4 4 3]

In [21]:
import numpy as np
arr=np.random.randint(0,5,12)
res=np.reshape(arr,(3,4))
print(res)

[[4 3 4 3]
 [0 3 2 2]
 [1 4 2 4]]

In [23]:
import numpy as np
arr=np.random.randint(0,10,size=(3,3))
print(arr)

[[1 1 7]
 [7 7 0]
 [1 7 4]]

In [29]:
import pandas as pd

In [31]:
data={
    "name":["arfath","zama","muskan"],
    "age":[10,20,30],
    "fav movie":["salli","malli","kalli"]
}
print(data)

{'name': ['arfath', 'zama', 'muskan'], 'age': [10, 20, 30], 'fav movie': ['salli', 'malli', 'kalli']}

In [39]:
data={
    "name":["arfath","zama","muskan"],
    "age":[10,20,30],
    "fav movie":["salli","malli","kalli"]
}
df=pd.DataFrame(data)
display(df)

     name  age fav movie
0  arfath   10     salli
1    zama   20     malli
2  muskan   30     kalli

In [41]:
df["relation"]=["me","brother","sister"]
display(df)

     name  age fav movie relation
0  arfath   10     salli       me
1    zama   20     malli  brother
2  muskan   30     kalli   sister

In [42]:
filterData=df["age"]>=10
display(filterData)

0    False
1     True
2     True
Name: age, dtype: bool

In [45]:
filterData=df[df["age"]>=12]
display(filterData)

     name  age fav movie relation
1    zama   20     malli  brother
2  muskan   30     kalli   sister

In [46]:
display(df)

     name  age fav movie relation
0  arfath   10     salli       me
1    zama   20     malli  brother
2  muskan   30     kalli   sister

In [48]:
df.to_csv("student.csv",index=False)