In [1]:
import numpy as np
from scipy.stats import skew

data=[1,2,2,3,3,3,4,4,4,4]
skewness=skew(data)
print(skewness)

-0.6

In [2]:
# skewness formula
#skewness=(mean-mode)/SD

In [6]:
data=[1,2,2,3,3,3,4,4,4,4]
mean_value=np.mean(data)
mean_value

np.float64(3.0)

In [4]:
data=[1,2,2,3,3,3,4,4,4,4]
std_dev=np.std(data)
std_dev

np.float64(1.0)

In [5]:
data=[1,2,2,3,3,3,4,4,4,4]
mode_value=np.mode(data)
std_dev

AttributeError: module 'numpy' has no attribute 'mode'

In [8]:
from statistics import mode
data=[1,2,2,3,3,3,4,4,4,4]
mode_value=mode(data)
mode_value

4

In [10]:
skewness=(mean_value-mode_value)/std_dev
skewness

np.float64(-1.0)

In [ ]:
import numpy as np
from scipy.stats import skew

data=[1,2,2,3,3,3,4,4,4,4]
skewness=skew(data)
print(skewness)

In [11]:
import pandas as pd

In [13]:
df=pd.read_csv("date and temperature")

In [15]:
df

         Date  Temperature
0  2024-01-01            25
1  2024-01-02            28
2  2024-01-03            26
3  2024-01-04             5
4  2024-01-05            10
5  2024-01-05             4
6  2024-01-06             6
7  2024-01-07             9
8  2024-01-08             1

In [16]:
df["Date"]

0    2024-01-01
1    2024-01-02
2    2024-01-03
3    2024-01-04
4    2024-01-05
5    2024-01-05
6    2024-01-06
7    2024-01-07
8    2024-01-08
Name: Date, dtype: object

In [17]:
df["Temperature "]

0    25
1    28
2    26
3     5
4    10
5     4
6     6
7     9
8     1
Name: Temperature , dtype: int64

In [18]:
skewness=df["Temperature "].skew()
skewness

np.float64(0.646138463164241)

In [20]:
if skewness<0:
 print("temperature are negatively skewed,meaning there are more lower teperature")
elif skewness>0:
  print("temperature are positively skewed,meaning there are more higher teperature")
else:
  print("temperature are positively skewed")

temperature are positively skewed,meaning there are more higher teperature