In [2]:
import numpy as np

In [3]:
data=[10,20,40,60,50,]

In [6]:
std_dev=np.std(data)

In [7]:
std_dev

np.float64(18.547236990991408)

In [ ]:
# Is it spread out?

In [8]:
mean_value=np.mean(data)
print(mean_value)

36.0

In [10]:
if std_dev>mean_value:
  print("the data is spreadout")
else:
  print("the data is not spread out")

the data is not spread out

In [ ]:
# combining complete code in one set

In [ ]:
import numpy as np
#data set
data=[10,20,40,60,50]
#Calculate the standard deviation
std_dev=np.std(data)
print("the standarad deviation is",std_dev)
#Calculate the mean value
mean_value=np.mean(data)
print("the mean value is",mean_value)
#to check wheather it is spread out or not
if std_dev>mean_value:
  print("the data is spread out")
else:
  print("the data is not spread out")

the standarad deviation is 18.547236990991408
the mean value is 36.0
the data is not spread out

In [14]:
import pandas as pd

In [56]:
pd.read_csv("salary123.csv")

   emp_id          salary
0       1           50000
1       2           60000
2       3           50000
3       5           70000
4       6           80000

In [76]:

df=pd.read_csv("salary123.csv")
df

   emp_id          salary
0       1           50000
1       2           60000
2       3           50000
3       5           70000
4       6           80000

In [77]:
df

   emp_id          salary
0       1           50000
1       2           60000
2       3           50000
3       5           70000
4       6           80000

In [81]:
std_dev=df["salary"].std()
std_dev

13038.404810405298

In [79]:
df.columns = df.columns.str.strip()

In [80]:
mean_value=df["salary"].mean()
mean_value

np.float64(62000.0)

In [82]:
if std_dev>mean_value:
  print("the data is spread out")
else:
  print("the data is not spread out")

the data is not spread out